### ISSUE TITLE
just got banned

### ISSUE THREAD

**Issue by sebyg666** [H4vC/PoeHud#92] opened 2015-11-05 23:39 UTC
Im assuming its poe hud. was in darkshrines when i got banned. i thaught this didnt change memory in anyway. also at no time did i spam create zones or anything like that, i just played normally

**Comment by H4vC** [comment] 2015-11-05 23:40
haven't checked the AC in a long time. Although I doubt they'd come after poehud after this much leniency.
I'll go check tomorrow or something.

**Comment by sebyg666** [comment] 2015-11-05 23:41
using vmv's version, that he updated for darkshrines but i couldnt post issue on his since its forked i beleive.
also several people on the forum for poehud are saying they just got banned same time as me

**Comment by H4vC** [comment] 2015-11-05 23:43
Yep confirming new ac stuff I'll look into it sorry for everyone who's been banned although I take no responsability haven't really touched the project in like 4 months or more.

**Comment by ghost** [comment] 2015-11-05 23:43
i'm using this version since 2 days and nothing happen so far...dunno, maybe is something wrong

**Comment by sebyg666** [comment] 2015-11-05 23:44
maybe, either way i messaged poe to ask why i got banned and will persist. obviously im playing the "i didnt do anything" card, we will see

**Comment by ghost** [comment] 2015-11-05 23:46
It's curious tho...i'm playing with 2 version at time, smad version and this one ,...weird.

**Comment by sebyg666** [comment] 2015-11-05 23:46
if you can post in the forum ask if anyone is using autohotkey scripts aswell. cos im using that too to fire multiple potions at once with 1 button

**Comment by Armux** [comment] 2015-11-06 00:12
I can confirm, banned 40min ago too.

**Comment by sebyg666** [comment] 2015-11-06 00:39
what in poehud could have possibly caused the ban i dont understand, unless GGG are actually using  software to infiltrate the memory of our system to see what programs are being run (which is illegal.... note that WoW used to do this and were found out)  then it doesnt make sence. Unless theres something in the code that changes memory.

**Comment by H4vC** [comment] 2015-11-06 00:40
Sig scans in any process, which they could do since forever but never actually did.

**Comment by sebyg666** [comment] 2015-11-06 00:41
wait sig scans in the game memory or the whole system of the player. theres a big difference

**Comment by H4vC** [comment] 2015-11-06 00:42
They could always scan processes that had a handle to the game. This isn't new.

**Comment by sebyg666** [comment] 2015-11-06 00:42
i had no idea that was even possible

**Comment by sebyg666** [comment] 2015-11-06 00:58
whats IDA that you mention in your forum post, just interested in knowing how you find out what the AC looks for.

**Comment by ghost** [comment] 2015-11-06 01:00
IDA is something more advanced then Cheat Engine...

**Comment by H4vC** [comment] 2015-11-06 01:00
IDA is a very powerful static analysis tool that I use to see a dissasembled version of the game so that I can grasp what it's doing.
It's not magical however and requires some x86 ASM knowledge.

**Comment by sebyg666** [comment] 2015-11-06 01:01
nice, sounds like a headache but fun. i dable in programming its why im interested. still anoyed at the ban purely due to the fact that the hud is just a helper not a hack. gona be hard to play without it really.

**Comment by ghost** [comment] 2015-11-06 01:05
Once you got used to the HUD...it's really stupid to play without..i tried and it's like i'm blind, deaf..:)

**Comment by sebyg666** [comment] 2015-11-06 01:05
lol yes exactly

**Comment by joesh1n** [comment] 2015-11-06 01:28
I wonder if there will be a way to recover

**Comment by sebyg666** [comment] 2015-11-06 01:29
i doubt it. perma ban is perma.

**Comment by H4vC** [comment] 2015-11-06 01:29
From the ban probably not, the HUD isn't dead we just need a lot more info on the AC in it's current state.

**Comment by joesh1n** [comment] 2015-11-06 01:32
Well then time to quit a game that I spent more than two thousand hours :(
It has worked perfectly for half a year by yesterday

**Comment by dopeshow** [comment] 2015-11-06 04:23
yep, banned. Rip PoE Hud....

**Comment by sebyg666** [comment] 2015-11-06 13:53
any news with the IDA, just read a post on reddit by chris_wilson saying people got banned for map-hacks, and tools that allowed you to see strongboxes on maps. Infact, here is his post..... 

""Basically, if you're running a program that interacts with Path of Exile, then it's counted as a third-party program.
The people banned were generally using map hacks, bots or programs that show what strongboxes are on a level, among other things.
There are some exceptions for very simple manually-triggered single-action macros, but in general, it's best to have a vanilla play experience.""

Still bafelled as to why some got banned and others didnt. had a friend playing same time as me with hud up and he didnt get banned. he turned his off as soon as i got banned though. No idea how he managed to get away with it.

**Comment by ghost** [comment] 2015-11-06 14:05
Do you use any of Procurement, Aquisition, some Antivirus...?
What about your friend..?
It's still weird how does a player with 3 huds opened and client hacked doesn't get banned and others do.
Someone mentioned on forum that 3 guys from his group got insta ban in the same time...this could mean that they use some sort of autoban hammer., and not manually or randomly ban players.

**Comment by sebyg666** [comment] 2015-11-06 14:10
i use aquisision but Devs already staed that procurement and aquisition do not interact with the game therefor they dont care. as for antivirus i use ESET nod32. i pay for it, so it better not have got me banned lol. I do want to say that when i started playing 3 months ago-ish, i did unknowingly use a bannable map hack for a week or so, maybe that put a mark on my account or something. I find it distastefull that they perma banned outright without a temp ban first for first offence or something. its very silly.

**Comment by stzokev** [comment] 2015-11-06 14:55
Did you pay for anything in the game? Maybe that is the difference between banned and others that got away with it.

**Comment by H4vC** [comment] 2015-11-06 14:57
That doesn't change a thing to be honest I have friends with thousands of dollars in mtx that got banned back on the maphack bans.

I'm going to close this thread there's nothing constructive going on here apart from speculation.

**Closed as completed by H4vC** 2015-11-06 14:57 UTC
